import { Component, OnInit } from '@angular/core';
import { Firestore } from '@angular/fire/firestore';
import { FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef } from '@angular/material/dialog';
import { collection, doc, setDoc } from 'firebase/firestore';
import { User } from 'src/models/user.class';

@Component({
  selector: 'app-dialog-add-user',
  templateUrl: './dialog-add-user.component.html',
  styleUrls: ['./dialog-add-user.component.scss'],
})
export class DialogAddUserComponent implements OnInit {
  firstFormGroup = this._formBuilder.group({
    firstName2: ['', Validators.required],
    lastName2: ['', Validators.required],
    birthdate2: '',
  });
  secondFormGroup = this._formBuilder.group({
    street: ['', Validators.required],
    zipCode: ['', Validators.required],
    city: ['', Validators.required],
  });
  thirdFormGroup = this._formBuilder.group({
    email: ['', Validators.required],
    phone: '',
  });
  isEditable = true;

  exampleUsers: object[] = [
    {
      firstName: 'Karlinda',
      lastName: 'Fiedler',
      companyname: 'Fiedler und Su00f6hne Holding GmbH',
      branch: 'Imobilien',
      street: 'Zum Dorental 17 Misserode',
      zipCode: '37308',
      city: 'Schimberg',
      homepage: 'https://www.fiedler.de',
      birthdate: '01.11.1944',
      email: 'karlinda@technikzq.de',
      userID: '24025894050232',
    },
    {
      firstName: 'Sylke',
      lastName: 'Schulz',
      companyname: 'Schulz & Partner GmbH',
      branch: 'Textil',
      street: 'Theodor-Heuss-Str. 26 ',
      zipCode: '49163',
      city: 'Bohmte',
      homepage: 'https://www.schulz.de',
      birthdate: '27.09.1990',
      email: 'info@zrp-communications.de',
      userID: '76704928474463',
    },
    {
      firstName: 'Helene',
      lastName: 'Baumgarten',
      companyname: 'Baumgarten Versicherung GmbH',
      branch: 'Versicherung',
      street: 'Heinrich-Fausel-Weg 39 ',
      zipCode: '88271',
      city: 'Wilhelmsdorf',
      birthdate: '09.06.1976',
      email: 'marketting@technikzq.de',
      userID: '14268867989727',
    },
    {
      firstName: 'Petja',
      lastName: 'Mann',
      companyname: 'Mann-Team Holding GmbH',
      branch: 'Dienstleistungen',
      street: 'Ringstr. 18 ',
      zipCode: '24994',
      city: 'Osterby',
      phone: '01515/61409426',
      birthdate: '15.05.1997',
      email: 'einkauf@technikzq.net',
      userID: '69263415440066',
    },
    {
      firstName: 'Annina',
      lastName: 'Lange',
      companyname: 'Lange und Söhne GmbH',
      branch: 'Automobil',
      street: 'Ötztaler Str. 6 Darmsheim',
      zipCode: '71069',
      city: 'Sindelfingen',
      birthdate: '17.06.1957',
      email: 'annina@zrp-communications.com',
      userID: '58687466934049',
    },
    {
      firstName: 'Line',
      lastName: 'Busch',
      companyname: 'Busch OHG',
      branch: 'Gastgewerbe',
      street: 'Weidenstr. 2 Affeln',
      zipCode: '58809',
      city: 'Neuenrade',
      phone: '0175/59490021',
      birthdate: '30.07.1952',
      email: 'l.busch@x-piros.info',
      userID: '27261853797838',
    },
    {
      firstName: 'Tenus',
      lastName: 'Schmidt',
      companyname: 'Schmidt-Team GbR',
      branch: 'Handwerk',
      street: 'Bahnhofstr. 34 Kempten',
      zipCode: '87435',
      city: 'Kempten (Allgäu)',
      birthdate: '24.07.1961',
      email: 'schmidt@blue-white.info',
      userID: '51634111713968',
    },
    {
      firstName: 'Leabelle',
      lastName: 'Brantley',
      companyname: 'Brantley-Group',
      branch: 'Recht',
      street: 'Wasserbreite 41A Sandhatten',
      zipCode: '26209',
      city: 'Hatten',
      homepage: 'www.brantley.info',
      birthdate: '16.06.1991',
      email: 'leabelle@technikzq.de',
      userID: '40169249781170',
    },
    {
      firstName: 'Thias',
      lastName: 'Muller',
      companyname: 'Muller GmbH',
      branch: 'Bau',
      street: 'Altenburg 43 ',
      zipCode: '83098',
      city: 'Brannenburg',
      phone: '0179/30906426',
      birthdate: '31.05.1935',
      email: 'thias@t-pomline.de',
      userID: '24735579699812',
    },
    {
      firstName: 'Noella',
      lastName: 'Bischoffs',
      companyname: 'Bischoffs International GmbH & Co. KG',
      street: 'Neuer Weg 24 ',
      zipCode: '39343',
      city: 'Erxleben',
      phone: '0176/77142336',
      birthdate: '21.01.2002',
      email: 'info@technikzq.de',
      userID: '90258799595248',
    },
    {
      firstName: 'Krista',
      lastName: 'Baumann',
      companyname: 'Baumann Energie Verwaltungs GmbH',
      branch: 'Energie',
      street: 'Eichendorffstr. 17 ',
      zipCode: '48703',
      city: 'Stadtlohn',
      phone: '0177/25641181',
      birthdate: '09.08.1948',
      email: 'krista.baumann@technikzq.de',
      userID: '75536387168980',
    },
    {
      firstName: 'Dietbert',
      lastName: 'Wolf',
      companyname: 'Wolf',
      branch: 'Gastgewerbe',
      street: 'Rotkehlchenweg 22 ',
      zipCode: '14547',
      city: 'Beelitz',
      phone: '0162/38406742',
      homepage: 'www.wolf.biz',
      birthdate: '03.11.1960',
      email: 'info@qt-power.de',
      userID: '85539445539073',
    },
    {
      firstName: 'Ringo',
      lastName: 'Große',
      companyname: 'Große Verwaltungs GmbH',
      branch: 'Handwerk',
      street: 'An den Klärteichen 20 Püsselbüren',
      zipCode: '49479',
      city: 'Ibbenbüren',
      phone: '0177/25595888',
      birthdate: '26.03.1947',
      email: 'info@extend.de',
      userID: '70205776699561',
    },
    {
      firstName: 'Basta',
      lastName: 'Schäfer',
      companyname: 'Schäfer Restaurant AG',
      branch: 'Restaurant',
      street: 'Birkenweg 29 ',
      zipCode: '86932',
      city: 'Pürgen',
      phone: '01522/94686893',
      birthdate: '15.04.1982',
      email: 'schfer@extend.net',
      userID: '95764032896104',
    },
    {
      firstName: 'Herbert',
      lastName: 'Bachman',
      companyname: 'Bachman',
      branch: 'Software',
      street: 'Günther-Laukien-Str. 10 Mörsch',
      zipCode: '76287',
      city: 'Rheinstetten',
      birthdate: '07.10.1993',
      email: 'info@zo-texit.com',
      userID: '54525048937935',
    },
    {
      firstName: 'Tido',
      lastName: 'Langer',
      companyname: 'Langer GmbH & Co. KG',
      branch: 'Telekomunikation',
      street: 'Eulenweg 39 Wehberg',
      zipCode: '58507',
      city: 'Lüdenscheid',
      phone: '01512/56145391',
      homepage: 'langer.net',
      birthdate: '01.06.1940',
      email: 'info@blue-white.info',
      userID: '79188813639637',
    },
    {
      firstName: 'Richenza',
      lastName: 'Seidel',
      companyname: 'Seidel-Team GbR',
      branch: 'Chemie',
      street: 'Am Gansberg 31 ',
      zipCode: '09481',
      city: 'Elterlein',
      homepage: 'http://seidel.de',
      birthdate: '05.06.1946',
      email: 'richenza@qt-power.de',
      userID: '68973681342021',
    },
    {
      firstName: 'Babsi',
      lastName: 'Krauss',
      companyname: 'Krauss-Team GmbH',
      branch: 'Bau',
      street: 'Am Becherweg 20 ',
      zipCode: '55270',
      city: 'Ober-Olm',
      birthdate: '28.01.1965',
      email: 'info@x-piros.de',
      userID: '64469281256449',
    },
    {
      firstName: 'Dietlinde',
      lastName: 'Wagner',
      companyname: 'Wagner-Team Verwaltungs GmbH',
      branch: 'Kino',
      street: 'Kreuzbergring 15 Furpach',
      zipCode: '66539',
      city: 'Neunkirchen',
      phone: '0176/80474623',
      birthdate: '18.06.1970',
      email: 'einkauf@extend.com',
      userID: '48091856814324',
    },
    {
      firstName: 'Lientje',
      lastName: 'Höfler',
      companyname: 'Höfler & Partner GbR',
      street: 'Kiefernhain 27 Lenz-Süd',
      zipCode: '17213',
      city: 'Fünfseen',
      homepage: 'http://www.hfler.de',
      birthdate: '11.01.1997',
      email: 'personal@comm-prefix.de',
      userID: '73216324843335',
    },
    {
      firstName: 'Deik',
      lastName: 'Wirth',
      companyname: 'Wirth International GmbH & Co. KG',
      street: 'Zauer Dorfstr. 20 Zaue',
      zipCode: '15913',
      city: 'Schwielochsee',
      phone: '01575/18707349',
      birthdate: '08.07.2002',
      email: 'd.wirth@comm-prefix.de',
      userID: '52866782045717',
    },
    {
      firstName: 'Beath',
      lastName: 'Beckert',
      companyname: 'Beckert',
      branch: 'Handel',
      street: 'Untere Parkstr. 38 ',
      zipCode: '06295',
      city: 'Lutherstadt Eisleben',
      phone: '0176/87242009',
      birthdate: '28.02.1947',
      email: 'info@blue-white.biz',
      userID: '84457154599941',
    },
    {
      firstName: 'Salvina',
      lastName: 'Haberkorn',
      companyname: 'Haberkorn Holding GmbH',
      street: 'Feldstr. 20 ',
      zipCode: '82380',
      city: 'Peißenberg',
      phone: '01573/61492417',
      birthdate: '20.06.1959',
      email: 's.haberkorn@comm-prefix.de',
      userID: '66120726221305',
    },
    {
      firstName: 'Hanneli',
      lastName: 'Wruck',
      companyname: 'Wruck Versicherung Holding GmbH',
      branch: 'Versicherung',
      street: 'Broichkirchweg 29 Kelz',
      zipCode: '52391',
      city: 'Vettweiß',
      birthdate: '17.04.1953',
      userID: '54961597546758',
    },
    {
      firstName: 'Londar',
      lastName: 'Tschida',
      companyname: 'Tschida-Group AG',
      branch: 'Bau',
      street: 'Saßnitzer Weg 28 Rahlstedt',
      zipCode: '22147',
      city: 'Hamburg',
      phone: '0163/88179989',
      birthdate: '24.05.1975',
      email: 'l.tschida@x-piros.com',
      userID: '68740529113648',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Brose',
      companyname: 'Brose-Group',
      branch: 'Pharmazie',
      street: 'Markusstr. 1B Pfaffenrot',
      zipCode: '76359',
      city: 'Marxzell',
      phone: '01517/43018473',
      homepage: 'www.brose.com',
      birthdate: '07.03.1963',
      email: 'info@no-addr.net',
      userID: '24055098054842',
    },
    {
      firstName: 'Samoa',
      lastName: 'Graner',
      companyname: 'Graner & Partner AG',
      branch: 'Bildung',
      street: 'Carl-Meyer-Str. 12 Böhlitz-Ehrenberg',
      zipCode: '04178',
      city: 'Leipzig',
      phone: '01573/32859099',
      birthdate: '25.01.1935',
      email: 'logistik@t-pomline.de',
      userID: '22481197890186',
    },
    {
      firstName: 'Marie Luise',
      lastName: 'Lewerentz',
      companyname: 'Lewerentz Media AG',
      branch: 'Media',
      street: 'Königsberger Str. 26 ',
      zipCode: '65830',
      city: 'Kriftel',
      phone: '0176/61982093',
      homepage: 'www.lewerentz.net',
      birthdate: '31.05.1934',
      email: 'marieluise.lewerentz@zrp-communications.de',
      userID: '25850296317081',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Vogel',
      companyname: 'Vogel-Group GmbH',
      street: 'Oranienstr. 25 Langenhain',
      zipCode: '65719',
      city: 'Hofheim am Taunus',
      phone: '01516/77590250',
      birthdate: '28.08.1942',
      email: 'einkauf@zo-texit.com',
      userID: '76078395669809',
    },
    {
      firstName: 'Archus',
      lastName: 'Oppenheimer',
      companyname: 'Oppenheimer-Group GmbH',
      branch: 'Dienstleistungen',
      street: 'In der Reitenwies 2 Theley',
      zipCode: '66636',
      city: 'Tholey',
      phone: '01570/69112937',
      homepage: 'http://www.oppenheimer.de',
      birthdate: '15.10.1942',
      email: 'archus@t-pomline.com',
      userID: '82745099798788',
    },
    {
      firstName: 'Florian',
      lastName: 'Kerner',
      companyname: 'Kerner-Group GmbH',
      street: 'Im Meilesfeld 3 Marksuhl',
      zipCode: '99834',
      city: 'Gerstungen',
      homepage: 'http://www.kerner.com',
      birthdate: '01.02.1949',
      email: 'f.kerner@zrp-communications.de',
      userID: '11762867755264',
    },
    {
      firstName: 'Lars',
      lastName: 'Reier',
      companyname: 'Reier Holding GmbH',
      branch: 'Gesundheit',
      street: 'Seidiek 19 Lembeck',
      zipCode: '46286',
      city: 'Dorsten',
      birthdate: '26.03.2002',
      email: 'logistik@qt-power.de',
      userID: '39364079884599',
    },
    {
      firstName: 'Franziskus',
      lastName: 'Blumenthal',
      companyname: 'Blumenthal Kino AG',
      street: 'Gildestr. 5 ',
      zipCode: '48465',
      city: 'Schüttorf',
      homepage: 'www.blumenthal.de',
      birthdate: '28.10.1976',
      userID: '72944755471714',
    },
    {
      firstName: 'Denise',
      lastName: 'Becker',
      companyname: 'Becker-Team',
      branch: 'Restaurant',
      street: 'Ostfriesenweg 23 Rahrdum',
      zipCode: '26441',
      city: 'Jever',
      birthdate: '22.04.1941',
      email: 'becker@no-addr.info',
      userID: '14541552871346',
    },
    {
      firstName: 'Bendine',
      lastName: 'Beckert',
      companyname: 'Beckert-Team Verwaltungs GmbH',
      branch: 'Ärzte',
      street: 'Am Hegeberg 18 Viermünden',
      zipCode: '35066',
      city: 'Frankenberg',
      birthdate: '03.05.1984',
      email: 'bendine@company.net',
      userID: '45056645433022',
    },
    {
      firstName: 'Kastulus',
      lastName: 'Baasch',
      companyname: 'Baasch und Söhne e.K.',
      branch: 'Elektroinstallationen',
      street: 'Von-Frays-Str. 38 Pasing-Obermenzing',
      zipCode: '81245',
      city: 'München',
      phone: '0172/69513876',
      birthdate: '15.10.1945',
      email: 'marketting@blue-white.de',
      userID: '31211014482881',
    },
    {
      firstName: 'Sophie',
      lastName: 'Kranz',
      companyname: 'Kranz International',
      branch: 'Energie',
      street: 'Diekenkamp 25 ',
      zipCode: '26419',
      city: 'Schortens',
      birthdate: '26.06.1952',
      userID: '63188719209362',
    },
    {
      firstName: 'Wienand',
      lastName: 'Wetzel',
      companyname: 'Wetzel Unterhaltung Verwaltungs GmbH',
      branch: 'Unterhaltung',
      street: 'Heuweg 44 Eglosheim',
      zipCode: '71634',
      city: 'Ludwigsburg',
      birthdate: '09.09.1969',
      email: 'wetzel@extend.de',
      userID: '25066689006399',
    },
    {
      firstName: 'Oke',
      lastName: 'Zimmermann',
      companyname: 'Zimmermann International',
      branch: 'Kultur',
      street: 'Stockfeldstr. 32 Stift Quernheim',
      zipCode: '32278',
      city: 'Kirchlengern',
      birthdate: '28.06.1954',
      email: 'zimmermann@comm-prefix.de',
      userID: '35924612368082',
    },
    {
      firstName: 'Xandy',
      lastName: 'Weber',
      companyname: 'Weber GmbH',
      branch: 'Medizin',
      street: 'Ackerbürgerweg 26 ',
      zipCode: '59348',
      city: 'Lüdinghausen',
      phone: '0175/79764978',
      homepage: 'weber.de',
      birthdate: '04.12.1942',
      email: 'xandy@zrp-communications.com',
      userID: '79982434694606',
    },
    {
      firstName: 'Daniel',
      lastName: 'Mann',
      companyname: 'Mann und Söhne GmbH',
      street: 'Am Zuschlag 4 Lohne',
      zipCode: '49393',
      city: 'Lohne (Oldenburg)',
      birthdate: '08.06.1968',
      userID: '19461364415149',
    },
    {
      firstName: 'Rawia',
      lastName: 'Weber',
      companyname: 'Weber OHG',
      branch: 'Automobil',
      street: 'Metzwies`chen 17 ',
      zipCode: '54634',
      city: 'Bitburg',
      homepage: 'http://weber.com',
      birthdate: '01.11.1965',
      userID: '68578703777621',
    },
    {
      firstName: 'Melanie',
      lastName: 'Kappel',
      companyname: 'Kappel International',
      street: 'Brittener Str. 34 Britten',
      zipCode: '66679',
      city: 'Losheim am See',
      birthdate: '26.02.1998',
      email: 'einkauf@t-pomline.de',
      userID: '35974639025620',
    },
    {
      firstName: 'Fabian',
      lastName: 'Saller',
      companyname: 'Saller GmbH',
      branch: 'Veranstaltungen',
      street: 'Hubertusstr. 5 Gey',
      zipCode: '52393',
      city: 'Hürtgenwald',
      phone: '01522/16231793',
      homepage: 'http://www.saller.info',
      birthdate: '23.03.1955',
      email: 'fabian@qt-power.info',
      userID: '47201488193811',
    },
    {
      firstName: 'Revelyn',
      lastName: 'Ludwig',
      companyname: 'Ludwig & Partner e.K.',
      street: 'Karlsfeldstr. 15 Friedrichstal',
      zipCode: '76297',
      city: 'Stutensee',
      birthdate: '07.07.1938',
      userID: '56503291539909',
    },
    {
      firstName: 'Kim',
      lastName: 'Höfler',
      companyname: 'Höfler Steuern GbR',
      branch: 'Steuern',
      street: 'Herbststr. 35 ',
      zipCode: '74626',
      city: 'Bretzfeld',
      birthdate: '29.11.1964',
      email: 'hfler@no-addr.de',
      userID: '96653864306320',
    },
    {
      firstName: 'Tim',
      lastName: 'Arbeit',
      companyname: 'Arbeit Forschung OHG',
      branch: 'Forschung',
      street: 'Siemensstr. 16 ',
      zipCode: '85521',
      city: 'Ottobrunn',
      homepage: 'http://www.arbeit.info',
      birthdate: '05.01.1984',
      email: 'marketting@t-pomline.de',
      userID: '41824331322752',
    },
    {
      firstName: 'Lisbeth',
      lastName: 'Koch',
      companyname: 'Koch',
      branch: 'Textil',
      street: 'Renthof 5 ',
      zipCode: '34329',
      city: 'Nieste',
      birthdate: '21.04.1977',
      email: 'lisbeth.koch@comm-prefix.de',
      userID: '23483921198321',
    },
    {
      firstName: 'Rosfriede',
      lastName: 'Schwarz',
      companyname: 'Schwarz',
      branch: 'Forschung',
      street: 'Mittelweg 24 Feldschlößchen',
      zipCode: '01454',
      city: 'Wachau',
      phone: '01514/85418816',
      birthdate: '27.04.1978',
      email: 'rosfriede@blue-white.com',
      userID: '56336811622422',
    },
    {
      firstName: 'Griselda',
      lastName: 'Höfler',
      companyname: 'Höfler GmbH',
      branch: 'Verkehr',
      street: 'Dompfaffstr. 19 Alterlangen',
      zipCode: '91056',
      city: 'Erlangen',
      homepage: 'https://www.hfler.de',
      birthdate: '30.09.1937',
      email: 'logistik@zo-texit.de',
      userID: '39699706727259',
    },
    {
      firstName: 'Karlinda',
      lastName: 'Fiedler',
      companyname: 'Fiedler und Söhne Holding GmbH',
      branch: 'Imobilien',
      street: 'Zum Dorental 17 Misserode',
      zipCode: '37308',
      city: 'Schimberg',
      homepage: 'https://www.fiedler.de',
      birthdate: '01.11.1944',
      email: 'karlinda@technikzq.de',
      userID: '24025894050232',
    },
    {
      firstName: 'Sylke',
      lastName: 'Schulz',
      companyname: 'Schulz & Partner GmbH',
      branch: 'Textil',
      street: 'Theodor-Heuss-Str. 26 ',
      zipCode: '49163',
      city: 'Bohmte',
      homepage: 'https://www.schulz.de',
      birthdate: '27.09.1990',
      email: 'info@zrp-communications.de',
      userID: '76704928474463',
    },
    {
      firstName: 'Helene',
      lastName: 'Baumgarten',
      companyname: 'Baumgarten Versicherung GmbH',
      branch: 'Versicherung',
      street: 'Heinrich-Fausel-Weg 39 ',
      zipCode: '88271',
      city: 'Wilhelmsdorf',
      birthdate: '09.06.1976',
      email: 'marketting@technikzq.de',
      userID: '14268867989727',
    },
    {
      firstName: 'Petja',
      lastName: 'Mann',
      companyname: 'Mann-Team Holding GmbH',
      branch: 'Dienstleistungen',
      street: 'Ringstr. 18 ',
      zipCode: '24994',
      city: 'Osterby',
      phone: '01515/61409426',
      birthdate: '15.05.1997',
      email: 'einkauf@technikzq.net',
      userID: '69263415440066',
    },
    {
      firstName: 'Annina',
      lastName: 'Lange',
      companyname: 'Lange und Söhne GmbH',
      branch: 'Automobil',
      street: 'Ötztaler Str. 6 Darmsheim',
      zipCode: '71069',
      city: 'Sindelfingen',
      birthdate: '17.06.1957',
      email: 'annina@zrp-communications.com',
      userID: '58687466934049',
    },
    {
      firstName: 'Line',
      lastName: 'Busch',
      companyname: 'Busch OHG',
      branch: 'Gastgewerbe',
      street: 'Weidenstr. 2 Affeln',
      zipCode: '58809',
      city: 'Neuenrade',
      phone: '0175/59490021',
      birthdate: '30.07.1952',
      email: 'l.busch@x-piros.info',
      userID: '27261853797838',
    },
    {
      firstName: 'Tenus',
      lastName: 'Schmidt',
      companyname: 'Schmidt-Team GbR',
      branch: 'Handwerk',
      street: 'Bahnhofstr. 34 Kempten',
      zipCode: '87435',
      city: 'Kempten (Allgäu)',
      birthdate: '24.07.1961',
      email: 'schmidt@blue-white.info',
      userID: '51634111713968',
    },
    {
      firstName: 'Leabelle',
      lastName: 'Brantley',
      companyname: 'Brantley-Group',
      branch: 'Recht',
      street: 'Wasserbreite 41A Sandhatten',
      zipCode: '26209',
      city: 'Hatten',
      homepage: 'www.brantley.info',
      birthdate: '16.06.1991',
      email: 'leabelle@technikzq.de',
      userID: '40169249781170',
    },
    {
      firstName: 'Thias',
      lastName: 'Muller',
      companyname: 'Muller GmbH',
      branch: 'Bau',
      street: 'Altenburg 43 ',
      zipCode: '83098',
      city: 'Brannenburg',
      phone: '0179/30906426',
      birthdate: '31.05.1935',
      email: 'thias@t-pomline.de',
      userID: '24735579699812',
    },
    {
      firstName: 'Noella',
      lastName: 'Bischoffs',
      companyname: 'Bischoffs International GmbH & Co. KG',
      street: 'Neuer Weg 24 ',
      zipCode: '39343',
      city: 'Erxleben',
      phone: '0176/77142336',
      birthdate: '21.01.2002',
      email: 'info@technikzq.de',
      userID: '90258799595248',
    },
    {
      firstName: 'Krista',
      lastName: 'Baumann',
      companyname: 'Baumann Energie Verwaltungs GmbH',
      branch: 'Energie',
      street: 'Eichendorffstr. 17 ',
      zipCode: '48703',
      city: 'Stadtlohn',
      phone: '0177/25641181',
      birthdate: '09.08.1948',
      email: 'krista.baumann@technikzq.de',
      userID: '75536387168980',
    },
    {
      firstName: 'Dietbert',
      lastName: 'Wolf',
      companyname: 'Wolf',
      branch: 'Gastgewerbe',
      street: 'Rotkehlchenweg 22 ',
      zipCode: '14547',
      city: 'Beelitz',
      phone: '0162/38406742',
      homepage: 'www.wolf.biz',
      birthdate: '03.11.1960',
      email: 'info@qt-power.de',
      userID: '85539445539073',
    },
    {
      firstName: 'Ringo',
      lastName: 'Große',
      companyname: 'Große Verwaltungs GmbH',
      branch: 'Handwerk',
      street: 'An den Klärteichen 20 Püsselbüren',
      zipCode: '49479',
      city: 'Ibbenbüren',
      phone: '0177/25595888',
      birthdate: '26.03.1947',
      email: 'info@extend.de',
      userID: '70205776699561',
    },
    {
      firstName: 'Basta',
      lastName: 'Schäfer',
      companyname: 'Schäfer Restaurant AG',
      branch: 'Restaurant',
      street: 'Birkenweg 29 ',
      zipCode: '86932',
      city: 'Pürgen',
      phone: '01522/94686893',
      birthdate: '15.04.1982',
      email: 'schfer@extend.net',
      userID: '95764032896104',
    },
    {
      firstName: 'Herbert',
      lastName: 'Bachman',
      companyname: 'Bachman',
      branch: 'Software',
      street: 'Günther-Laukien-Str. 10 Mörsch',
      zipCode: '76287',
      city: 'Rheinstetten',
      birthdate: '07.10.1993',
      email: 'info@zo-texit.com',
      userID: '54525048937935',
    },
    {
      firstName: 'Tido',
      lastName: 'Langer',
      companyname: 'Langer GmbH & Co. KG',
      branch: 'Telekomunikation',
      street: 'Eulenweg 39 Wehberg',
      zipCode: '58507',
      city: 'Lüdenscheid',
      phone: '01512/56145391',
      homepage: 'langer.net',
      birthdate: '01.06.1940',
      email: 'info@blue-white.info',
      userID: '79188813639637',
    },
    {
      firstName: 'Richenza',
      lastName: 'Seidel',
      companyname: 'Seidel-Team GbR',
      branch: 'Chemie',
      street: 'Am Gansberg 31 ',
      zipCode: '09481',
      city: 'Elterlein',
      homepage: 'http://seidel.de',
      birthdate: '05.06.1946',
      email: 'richenza@qt-power.de',
      userID: '68973681342021',
    },
    {
      firstName: 'Babsi',
      lastName: 'Krauss',
      companyname: 'Krauss-Team GmbH',
      branch: 'Bau',
      street: 'Am Becherweg 20 ',
      zipCode: '55270',
      city: 'Ober-Olm',
      birthdate: '28.01.1965',
      email: 'info@x-piros.de',
      userID: '64469281256449',
    },
    {
      firstName: 'Dietlinde',
      lastName: 'Wagner',
      companyname: 'Wagner-Team Verwaltungs GmbH',
      branch: 'Kino',
      street: 'Kreuzbergring 15 Furpach',
      zipCode: '66539',
      city: 'Neunkirchen',
      phone: '0176/80474623',
      birthdate: '18.06.1970',
      email: 'einkauf@extend.com',
      userID: '48091856814324',
    },
    {
      firstName: 'Lientje',
      lastName: 'Höfler',
      companyname: 'Höfler & Partner GbR',
      street: 'Kiefernhain 27 Lenz-Süd',
      zipCode: '17213',
      city: 'Fünfseen',
      homepage: 'http://www.hfler.de',
      birthdate: '11.01.1997',
      email: 'personal@comm-prefix.de',
      userID: '73216324843335',
    },
    {
      firstName: 'Deik',
      lastName: 'Wirth',
      companyname: 'Wirth International GmbH & Co. KG',
      street: 'Zauer Dorfstr. 20 Zaue',
      zipCode: '15913',
      city: 'Schwielochsee',
      phone: '01575/18707349',
      birthdate: '08.07.2002',
      email: 'd.wirth@comm-prefix.de',
      userID: '52866782045717',
    },
    {
      firstName: 'Beath',
      lastName: 'Beckert',
      companyname: 'Beckert',
      branch: 'Handel',
      street: 'Untere Parkstr. 38 ',
      zipCode: '06295',
      city: 'Lutherstadt Eisleben',
      phone: '0176/87242009',
      birthdate: '28.02.1947',
      email: 'info@blue-white.biz',
      userID: '84457154599941',
    },
    {
      firstName: 'Salvina',
      lastName: 'Haberkorn',
      companyname: 'Haberkorn Holding GmbH',
      street: 'Feldstr. 20 ',
      zipCode: '82380',
      city: 'Peißenberg',
      phone: '01573/61492417',
      birthdate: '20.06.1959',
      email: 's.haberkorn@comm-prefix.de',
      userID: '66120726221305',
    },
    {
      firstName: 'Hanneli',
      lastName: 'Wruck',
      companyname: 'Wruck Versicherung Holding GmbH',
      branch: 'Versicherung',
      street: 'Broichkirchweg 29 Kelz',
      zipCode: '52391',
      city: 'Vettweiß',
      birthdate: '17.04.1953',
      userID: '54961597546758',
    },
    {
      firstName: 'Londar',
      lastName: 'Tschida',
      companyname: 'Tschida-Group AG',
      branch: 'Bau',
      street: 'Saßnitzer Weg 28 Rahlstedt',
      zipCode: '22147',
      city: 'Hamburg',
      phone: '0163/88179989',
      birthdate: '24.05.1975',
      email: 'l.tschida@x-piros.com',
      userID: '68740529113648',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Brose',
      companyname: 'Brose-Group',
      branch: 'Pharmazie',
      street: 'Markusstr. 1B Pfaffenrot',
      zipCode: '76359',
      city: 'Marxzell',
      phone: '01517/43018473',
      homepage: 'www.brose.com',
      birthdate: '07.03.1963',
      email: 'info@no-addr.net',
      userID: '24055098054842',
    },
    {
      firstName: 'Samoa',
      lastName: 'Graner',
      companyname: 'Graner & Partner AG',
      branch: 'Bildung',
      street: 'Carl-Meyer-Str. 12 Böhlitz-Ehrenberg',
      zipCode: '04178',
      city: 'Leipzig',
      phone: '01573/32859099',
      birthdate: '25.01.1935',
      email: 'logistik@t-pomline.de',
      userID: '22481197890186',
    },
    {
      firstName: 'Marie Luise',
      lastName: 'Lewerentz',
      companyname: 'Lewerentz Media AG',
      branch: 'Media',
      street: 'Königsberger Str. 26 ',
      zipCode: '65830',
      city: 'Kriftel',
      phone: '0176/61982093',
      homepage: 'www.lewerentz.net',
      birthdate: '31.05.1934',
      email: 'marieluise.lewerentz@zrp-communications.de',
      userID: '25850296317081',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Vogel',
      companyname: 'Vogel-Group GmbH',
      street: 'Oranienstr. 25 Langenhain',
      zipCode: '65719',
      city: 'Hofheim am Taunus',
      phone: '01516/77590250',
      birthdate: '28.08.1942',
      email: 'einkauf@zo-texit.com',
      userID: '76078395669809',
    },
    {
      firstName: 'Archus',
      lastName: 'Oppenheimer',
      companyname: 'Oppenheimer-Group GmbH',
      branch: 'Dienstleistungen',
      street: 'In der Reitenwies 2 Theley',
      zipCode: '66636',
      city: 'Tholey',
      phone: '01570/69112937',
      homepage: 'http://www.oppenheimer.de',
      birthdate: '15.10.1942',
      email: 'archus@t-pomline.com',
      userID: '82745099798788',
    },
    {
      firstName: 'Florian',
      lastName: 'Kerner',
      companyname: 'Kerner-Group GmbH',
      street: 'Im Meilesfeld 3 Marksuhl',
      zipCode: '99834',
      city: 'Gerstungen',
      homepage: 'http://www.kerner.com',
      birthdate: '01.02.1949',
      email: 'f.kerner@zrp-communications.de',
      userID: '11762867755264',
    },
    {
      firstName: 'Lars',
      lastName: 'Reier',
      companyname: 'Reier Holding GmbH',
      branch: 'Gesundheit',
      street: 'Seidiek 19 Lembeck',
      zipCode: '46286',
      city: 'Dorsten',
      birthdate: '26.03.2002',
      email: 'logistik@qt-power.de',
      userID: '39364079884599',
    },
    {
      firstName: 'Franziskus',
      lastName: 'Blumenthal',
      companyname: 'Blumenthal Kino AG',
      street: 'Gildestr. 5 ',
      zipCode: '48465',
      city: 'Schüttorf',
      homepage: 'www.blumenthal.de',
      birthdate: '28.10.1976',
      userID: '72944755471714',
    },
    {
      firstName: 'Denise',
      lastName: 'Becker',
      companyname: 'Becker-Team',
      branch: 'Restaurant',
      street: 'Ostfriesenweg 23 Rahrdum',
      zipCode: '26441',
      city: 'Jever',
      birthdate: '22.04.1941',
      email: 'becker@no-addr.info',
      userID: '14541552871346',
    },
    {
      firstName: 'Bendine',
      lastName: 'Beckert',
      companyname: 'Beckert-Team Verwaltungs GmbH',
      branch: 'Ärzte',
      street: 'Am Hegeberg 18 Viermünden',
      zipCode: '35066',
      city: 'Frankenberg',
      birthdate: '03.05.1984',
      email: 'bendine@company.net',
      userID: '45056645433022',
    },
    {
      firstName: 'Kastulus',
      lastName: 'Baasch',
      companyname: 'Baasch und Söhne e.K.',
      branch: 'Elektroinstallationen',
      street: 'Von-Frays-Str. 38 Pasing-Obermenzing',
      zipCode: '81245',
      city: 'München',
      phone: '0172/69513876',
      birthdate: '15.10.1945',
      email: 'marketting@blue-white.de',
      userID: '31211014482881',
    },
    {
      firstName: 'Sophie',
      lastName: 'Kranz',
      companyname: 'Kranz International',
      branch: 'Energie',
      street: 'Diekenkamp 25 ',
      zipCode: '26419',
      city: 'Schortens',
      birthdate: '26.06.1952',
      userID: '63188719209362',
    },
    {
      firstName: 'Wienand',
      lastName: 'Wetzel',
      companyname: 'Wetzel Unterhaltung Verwaltungs GmbH',
      branch: 'Unterhaltung',
      street: 'Heuweg 44 Eglosheim',
      zipCode: '71634',
      city: 'Ludwigsburg',
      birthdate: '09.09.1969',
      email: 'wetzel@extend.de',
      userID: '25066689006399',
    },
    {
      firstName: 'Oke',
      lastName: 'Zimmermann',
      companyname: 'Zimmermann International',
      branch: 'Kultur',
      street: 'Stockfeldstr. 32 Stift Quernheim',
      zipCode: '32278',
      city: 'Kirchlengern',
      birthdate: '28.06.1954',
      email: 'zimmermann@comm-prefix.de',
      userID: '35924612368082',
    },
    {
      firstName: 'Xandy',
      lastName: 'Weber',
      companyname: 'Weber GmbH',
      branch: 'Medizin',
      street: 'Ackerbürgerweg 26 ',
      zipCode: '59348',
      city: 'Lüdinghausen',
      phone: '0175/79764978',
      homepage: 'weber.de',
      birthdate: '04.12.1942',
      email: 'xandy@zrp-communications.com',
      userID: '79982434694606',
    },
    {
      firstName: 'Daniel',
      lastName: 'Mann',
      companyname: 'Mann und Söhne GmbH',
      street: 'Am Zuschlag 4 Lohne',
      zipCode: '49393',
      city: 'Lohne (Oldenburg)',
      birthdate: '08.06.1968',
      userID: '19461364415149',
    },
    {
      firstName: 'Rawia',
      lastName: 'Weber',
      companyname: 'Weber OHG',
      branch: 'Automobil',
      street: 'Metzwies`chen 17 ',
      zipCode: '54634',
      city: 'Bitburg',
      homepage: 'http://weber.com',
      birthdate: '01.11.1965',
      userID: '68578703777621',
    },
    {
      firstName: 'Melanie',
      lastName: 'Kappel',
      companyname: 'Kappel International',
      street: 'Brittener Str. 34 Britten',
      zipCode: '66679',
      city: 'Losheim am See',
      birthdate: '26.02.1998',
      email: 'einkauf@t-pomline.de',
      userID: '35974639025620',
    },
    {
      firstName: 'Fabian',
      lastName: 'Saller',
      companyname: 'Saller GmbH',
      branch: 'Veranstaltungen',
      street: 'Hubertusstr. 5 Gey',
      zipCode: '52393',
      city: 'Hürtgenwald',
      phone: '01522/16231793',
      homepage: 'http://www.saller.info',
      birthdate: '23.03.1955',
      email: 'fabian@qt-power.info',
      userID: '47201488193811',
    },
    {
      firstName: 'Revelyn',
      lastName: 'Ludwig',
      companyname: 'Ludwig & Partner e.K.',
      street: 'Karlsfeldstr. 15 Friedrichstal',
      zipCode: '76297',
      city: 'Stutensee',
      birthdate: '07.07.1938',
      userID: '56503291539909',
    },
    {
      firstName: 'Kim',
      lastName: 'Höfler',
      companyname: 'Höfler Steuern GbR',
      branch: 'Steuern',
      street: 'Herbststr. 35 ',
      zipCode: '74626',
      city: 'Bretzfeld',
      birthdate: '29.11.1964',
      email: 'hfler@no-addr.de',
      userID: '96653864306320',
    },
    {
      firstName: 'Tim',
      lastName: 'Arbeit',
      companyname: 'Arbeit Forschung OHG',
      branch: 'Forschung',
      street: 'Siemensstr. 16 ',
      zipCode: '85521',
      city: 'Ottobrunn',
      homepage: 'http://www.arbeit.info',
      birthdate: '05.01.1984',
      email: 'marketting@t-pomline.de',
      userID: '41824331322752',
    },
    {
      firstName: 'Lisbeth',
      lastName: 'Koch',
      companyname: 'Koch',
      branch: 'Textil',
      street: 'Renthof 5 ',
      zipCode: '34329',
      city: 'Nieste',
      birthdate: '21.04.1977',
      email: 'lisbeth.koch@comm-prefix.de',
      userID: '23483921198321',
    },
    {
      firstName: 'Rosfriede',
      lastName: 'Schwarz',
      companyname: 'Schwarz',
      branch: 'Forschung',
      street: 'Mittelweg 24 Feldschlößchen',
      zipCode: '01454',
      city: 'Wachau',
      phone: '01514/85418816',
      birthdate: '27.04.1978',
      email: 'rosfriede@blue-white.com',
      userID: '56336811622422',
    },
    {
      firstName: 'Griselda',
      lastName: 'Höfler',
      companyname: 'Höfler GmbH',
      branch: 'Verkehr',
      street: 'Dompfaffstr. 19 Alterlangen',
      zipCode: '91056',
      city: 'Erlangen',
      homepage: 'https://www.hfler.de',
      birthdate: '30.09.1937',
      email: 'logistik@zo-texit.de',
      userID: '39699706727259',
    },
    {
      firstName: 'Karlinda',
      lastName: 'Fiedler',
      companyname: 'Fiedler und Söhne Holding GmbH',
      branch: 'Imobilien',
      street: 'Zum Dorental 17 Misserode',
      zipCode: '37308',
      city: 'Schimberg',
      homepage: 'https://www.fiedler.de',
      birthdate: '01.11.1944',
      email: 'karlinda@technikzq.de',
      userID: '24025894050232',
    },
    {
      firstName: 'Sylke',
      lastName: 'Schulz',
      companyname: 'Schulz & Partner GmbH',
      branch: 'Textil',
      street: 'Theodor-Heuss-Str. 26 ',
      zipCode: '49163',
      city: 'Bohmte',
      homepage: 'https://www.schulz.de',
      birthdate: '27.09.1990',
      email: 'info@zrp-communications.de',
      userID: '76704928474463',
    },
    {
      firstName: 'Helene',
      lastName: 'Baumgarten',
      companyname: 'Baumgarten Versicherung GmbH',
      branch: 'Versicherung',
      street: 'Heinrich-Fausel-Weg 39 ',
      zipCode: '88271',
      city: 'Wilhelmsdorf',
      birthdate: '09.06.1976',
      email: 'marketting@technikzq.de',
      userID: '14268867989727',
    },
    {
      firstName: 'Petja',
      lastName: 'Mann',
      companyname: 'Mann-Team Holding GmbH',
      branch: 'Dienstleistungen',
      street: 'Ringstr. 18 ',
      zipCode: '24994',
      city: 'Osterby',
      phone: '01515/61409426',
      birthdate: '15.05.1997',
      email: 'einkauf@technikzq.net',
      userID: '69263415440066',
    },
    {
      firstName: 'Annina',
      lastName: 'Lange',
      companyname: 'Lange und Söhne GmbH',
      branch: 'Automobil',
      street: 'Ötztaler Str. 6 Darmsheim',
      zipCode: '71069',
      city: 'Sindelfingen',
      birthdate: '17.06.1957',
      email: 'annina@zrp-communications.com',
      userID: '58687466934049',
    },
    {
      firstName: 'Line',
      lastName: 'Busch',
      companyname: 'Busch OHG',
      branch: 'Gastgewerbe',
      street: 'Weidenstr. 2 Affeln',
      zipCode: '58809',
      city: 'Neuenrade',
      phone: '0175/59490021',
      birthdate: '30.07.1952',
      email: 'l.busch@x-piros.info',
      userID: '27261853797838',
    },
    {
      firstName: 'Tenus',
      lastName: 'Schmidt',
      companyname: 'Schmidt-Team GbR',
      branch: 'Handwerk',
      street: 'Bahnhofstr. 34 Kempten',
      zipCode: '87435',
      city: 'Kempten (Allgäu)',
      birthdate: '24.07.1961',
      email: 'schmidt@blue-white.info',
      userID: '51634111713968',
    },
    {
      firstName: 'Leabelle',
      lastName: 'Brantley',
      companyname: 'Brantley-Group',
      branch: 'Recht',
      street: 'Wasserbreite 41A Sandhatten',
      zipCode: '26209',
      city: 'Hatten',
      homepage: 'www.brantley.info',
      birthdate: '16.06.1991',
      email: 'leabelle@technikzq.de',
      userID: '40169249781170',
    },
    {
      firstName: 'Thias',
      lastName: 'Muller',
      companyname: 'Muller GmbH',
      branch: 'Bau',
      street: 'Altenburg 43 ',
      zipCode: '83098',
      city: 'Brannenburg',
      phone: '0179/30906426',
      birthdate: '31.05.1935',
      email: 'thias@t-pomline.de',
      userID: '24735579699812',
    },
    {
      firstName: 'Noella',
      lastName: 'Bischoffs',
      companyname: 'Bischoffs International GmbH & Co. KG',
      street: 'Neuer Weg 24 ',
      zipCode: '39343',
      city: 'Erxleben',
      phone: '0176/77142336',
      birthdate: '21.01.2002',
      email: 'info@technikzq.de',
      userID: '90258799595248',
    },
    {
      firstName: 'Krista',
      lastName: 'Baumann',
      companyname: 'Baumann Energie Verwaltungs GmbH',
      branch: 'Energie',
      street: 'Eichendorffstr. 17 ',
      zipCode: '48703',
      city: 'Stadtlohn',
      phone: '0177/25641181',
      birthdate: '09.08.1948',
      email: 'krista.baumann@technikzq.de',
      userID: '75536387168980',
    },
    {
      firstName: 'Dietbert',
      lastName: 'Wolf',
      companyname: 'Wolf',
      branch: 'Gastgewerbe',
      street: 'Rotkehlchenweg 22 ',
      zipCode: '14547',
      city: 'Beelitz',
      phone: '0162/38406742',
      homepage: 'www.wolf.biz',
      birthdate: '03.11.1960',
      email: 'info@qt-power.de',
      userID: '85539445539073',
    },
    {
      firstName: 'Ringo',
      lastName: 'Große',
      companyname: 'Große Verwaltungs GmbH',
      branch: 'Handwerk',
      street: 'An den Klärteichen 20 Püsselbüren',
      zipCode: '49479',
      city: 'Ibbenbüren',
      phone: '0177/25595888',
      birthdate: '26.03.1947',
      email: 'info@extend.de',
      userID: '70205776699561',
    },
    {
      firstName: 'Basta',
      lastName: 'Schäfer',
      companyname: 'Schäfer Restaurant AG',
      branch: 'Restaurant',
      street: 'Birkenweg 29 ',
      zipCode: '86932',
      city: 'Pürgen',
      phone: '01522/94686893',
      birthdate: '15.04.1982',
      email: 'schfer@extend.net',
      userID: '95764032896104',
    },
    {
      firstName: 'Herbert',
      lastName: 'Bachman',
      companyname: 'Bachman',
      branch: 'Software',
      street: 'Günther-Laukien-Str. 10 Mörsch',
      zipCode: '76287',
      city: 'Rheinstetten',
      birthdate: '07.10.1993',
      email: 'info@zo-texit.com',
      userID: '54525048937935',
    },
    {
      firstName: 'Tido',
      lastName: 'Langer',
      companyname: 'Langer GmbH & Co. KG',
      branch: 'Telekomunikation',
      street: 'Eulenweg 39 Wehberg',
      zipCode: '58507',
      city: 'Lüdenscheid',
      phone: '01512/56145391',
      homepage: 'langer.net',
      birthdate: '01.06.1940',
      email: 'info@blue-white.info',
      userID: '79188813639637',
    },
    {
      firstName: 'Richenza',
      lastName: 'Seidel',
      companyname: 'Seidel-Team GbR',
      branch: 'Chemie',
      street: 'Am Gansberg 31 ',
      zipCode: '09481',
      city: 'Elterlein',
      homepage: 'http://seidel.de',
      birthdate: '05.06.1946',
      email: 'richenza@qt-power.de',
      userID: '68973681342021',
    },
    {
      firstName: 'Babsi',
      lastName: 'Krauss',
      companyname: 'Krauss-Team GmbH',
      branch: 'Bau',
      street: 'Am Becherweg 20 ',
      zipCode: '55270',
      city: 'Ober-Olm',
      birthdate: '28.01.1965',
      email: 'info@x-piros.de',
      userID: '64469281256449',
    },
    {
      firstName: 'Dietlinde',
      lastName: 'Wagner',
      companyname: 'Wagner-Team Verwaltungs GmbH',
      branch: 'Kino',
      street: 'Kreuzbergring 15 Furpach',
      zipCode: '66539',
      city: 'Neunkirchen',
      phone: '0176/80474623',
      birthdate: '18.06.1970',
      email: 'einkauf@extend.com',
      userID: '48091856814324',
    },
    {
      firstName: 'Lientje',
      lastName: 'Höfler',
      companyname: 'Höfler & Partner GbR',
      street: 'Kiefernhain 27 Lenz-Süd',
      zipCode: '17213',
      city: 'Fünfseen',
      homepage: 'http://www.hfler.de',
      birthdate: '11.01.1997',
      email: 'personal@comm-prefix.de',
      userID: '73216324843335',
    },
    {
      firstName: 'Deik',
      lastName: 'Wirth',
      companyname: 'Wirth International GmbH & Co. KG',
      street: 'Zauer Dorfstr. 20 Zaue',
      zipCode: '15913',
      city: 'Schwielochsee',
      phone: '01575/18707349',
      birthdate: '08.07.2002',
      email: 'd.wirth@comm-prefix.de',
      userID: '52866782045717',
    },
    {
      firstName: 'Beath',
      lastName: 'Beckert',
      companyname: 'Beckert',
      branch: 'Handel',
      street: 'Untere Parkstr. 38 ',
      zipCode: '06295',
      city: 'Lutherstadt Eisleben',
      phone: '0176/87242009',
      birthdate: '28.02.1947',
      email: 'info@blue-white.biz',
      userID: '84457154599941',
    },
    {
      firstName: 'Salvina',
      lastName: 'Haberkorn',
      companyname: 'Haberkorn Holding GmbH',
      street: 'Feldstr. 20 ',
      zipCode: '82380',
      city: 'Peißenberg',
      phone: '01573/61492417',
      birthdate: '20.06.1959',
      email: 's.haberkorn@comm-prefix.de',
      userID: '66120726221305',
    },
    {
      firstName: 'Hanneli',
      lastName: 'Wruck',
      companyname: 'Wruck Versicherung Holding GmbH',
      branch: 'Versicherung',
      street: 'Broichkirchweg 29 Kelz',
      zipCode: '52391',
      city: 'Vettweiß',
      birthdate: '17.04.1953',
      userID: '54961597546758',
    },
    {
      firstName: 'Londar',
      lastName: 'Tschida',
      companyname: 'Tschida-Group AG',
      branch: 'Bau',
      street: 'Saßnitzer Weg 28 Rahlstedt',
      zipCode: '22147',
      city: 'Hamburg',
      phone: '0163/88179989',
      birthdate: '24.05.1975',
      email: 'l.tschida@x-piros.com',
      userID: '68740529113648',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Brose',
      companyname: 'Brose-Group',
      branch: 'Pharmazie',
      street: 'Markusstr. 1B Pfaffenrot',
      zipCode: '76359',
      city: 'Marxzell',
      phone: '01517/43018473',
      homepage: 'www.brose.com',
      birthdate: '07.03.1963',
      email: 'info@no-addr.net',
      userID: '24055098054842',
    },
    {
      firstName: 'Samoa',
      lastName: 'Graner',
      companyname: 'Graner & Partner AG',
      branch: 'Bildung',
      street: 'Carl-Meyer-Str. 12 Böhlitz-Ehrenberg',
      zipCode: '04178',
      city: 'Leipzig',
      phone: '01573/32859099',
      birthdate: '25.01.1935',
      email: 'logistik@t-pomline.de',
      userID: '22481197890186',
    },
    {
      firstName: 'Marie Luise',
      lastName: 'Lewerentz',
      companyname: 'Lewerentz Media AG',
      branch: 'Media',
      street: 'Königsberger Str. 26 ',
      zipCode: '65830',
      city: 'Kriftel',
      phone: '0176/61982093',
      homepage: 'www.lewerentz.net',
      birthdate: '31.05.1934',
      email: 'marieluise.lewerentz@zrp-communications.de',
      userID: '25850296317081',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Vogel',
      companyname: 'Vogel-Group GmbH',
      street: 'Oranienstr. 25 Langenhain',
      zipCode: '65719',
      city: 'Hofheim am Taunus',
      phone: '01516/77590250',
      birthdate: '28.08.1942',
      email: 'einkauf@zo-texit.com',
      userID: '76078395669809',
    },
    {
      firstName: 'Archus',
      lastName: 'Oppenheimer',
      companyname: 'Oppenheimer-Group GmbH',
      branch: 'Dienstleistungen',
      street: 'In der Reitenwies 2 Theley',
      zipCode: '66636',
      city: 'Tholey',
      phone: '01570/69112937',
      homepage: 'http://www.oppenheimer.de',
      birthdate: '15.10.1942',
      email: 'archus@t-pomline.com',
      userID: '82745099798788',
    },
    {
      firstName: 'Florian',
      lastName: 'Kerner',
      companyname: 'Kerner-Group GmbH',
      street: 'Im Meilesfeld 3 Marksuhl',
      zipCode: '99834',
      city: 'Gerstungen',
      homepage: 'http://www.kerner.com',
      birthdate: '01.02.1949',
      email: 'f.kerner@zrp-communications.de',
      userID: '11762867755264',
    },
    {
      firstName: 'Lars',
      lastName: 'Reier',
      companyname: 'Reier Holding GmbH',
      branch: 'Gesundheit',
      street: 'Seidiek 19 Lembeck',
      zipCode: '46286',
      city: 'Dorsten',
      birthdate: '26.03.2002',
      email: 'logistik@qt-power.de',
      userID: '39364079884599',
    },
    {
      firstName: 'Franziskus',
      lastName: 'Blumenthal',
      companyname: 'Blumenthal Kino AG',
      street: 'Gildestr. 5 ',
      zipCode: '48465',
      city: 'Schüttorf',
      homepage: 'www.blumenthal.de',
      birthdate: '28.10.1976',
      userID: '72944755471714',
    },
    {
      firstName: 'Denise',
      lastName: 'Becker',
      companyname: 'Becker-Team',
      branch: 'Restaurant',
      street: 'Ostfriesenweg 23 Rahrdum',
      zipCode: '26441',
      city: 'Jever',
      birthdate: '22.04.1941',
      email: 'becker@no-addr.info',
      userID: '14541552871346',
    },
    {
      firstName: 'Bendine',
      lastName: 'Beckert',
      companyname: 'Beckert-Team Verwaltungs GmbH',
      branch: 'Ärzte',
      street: 'Am Hegeberg 18 Viermünden',
      zipCode: '35066',
      city: 'Frankenberg',
      birthdate: '03.05.1984',
      email: 'bendine@company.net',
      userID: '45056645433022',
    },
    {
      firstName: 'Kastulus',
      lastName: 'Baasch',
      companyname: 'Baasch und Söhne e.K.',
      branch: 'Elektroinstallationen',
      street: 'Von-Frays-Str. 38 Pasing-Obermenzing',
      zipCode: '81245',
      city: 'München',
      phone: '0172/69513876',
      birthdate: '15.10.1945',
      email: 'marketting@blue-white.de',
      userID: '31211014482881',
    },
    {
      firstName: 'Sophie',
      lastName: 'Kranz',
      companyname: 'Kranz International',
      branch: 'Energie',
      street: 'Diekenkamp 25 ',
      zipCode: '26419',
      city: 'Schortens',
      birthdate: '26.06.1952',
      userID: '63188719209362',
    },
    {
      firstName: 'Wienand',
      lastName: 'Wetzel',
      companyname: 'Wetzel Unterhaltung Verwaltungs GmbH',
      branch: 'Unterhaltung',
      street: 'Heuweg 44 Eglosheim',
      zipCode: '71634',
      city: 'Ludwigsburg',
      birthdate: '09.09.1969',
      email: 'wetzel@extend.de',
      userID: '25066689006399',
    },
    {
      firstName: 'Oke',
      lastName: 'Zimmermann',
      companyname: 'Zimmermann International',
      branch: 'Kultur',
      street: 'Stockfeldstr. 32 Stift Quernheim',
      zipCode: '32278',
      city: 'Kirchlengern',
      birthdate: '28.06.1954',
      email: 'zimmermann@comm-prefix.de',
      userID: '35924612368082',
    },
    {
      firstName: 'Xandy',
      lastName: 'Weber',
      companyname: 'Weber GmbH',
      branch: 'Medizin',
      street: 'Ackerbürgerweg 26 ',
      zipCode: '59348',
      city: 'Lüdinghausen',
      phone: '0175/79764978',
      homepage: 'weber.de',
      birthdate: '04.12.1942',
      email: 'xandy@zrp-communications.com',
      userID: '79982434694606',
    },
    {
      firstName: 'Daniel',
      lastName: 'Mann',
      companyname: 'Mann und Söhne GmbH',
      street: 'Am Zuschlag 4 Lohne',
      zipCode: '49393',
      city: 'Lohne (Oldenburg)',
      birthdate: '08.06.1968',
      userID: '19461364415149',
    },
    {
      firstName: 'Rawia',
      lastName: 'Weber',
      companyname: 'Weber OHG',
      branch: 'Automobil',
      street: 'Metzwies`chen 17 ',
      zipCode: '54634',
      city: 'Bitburg',
      homepage: 'http://weber.com',
      birthdate: '01.11.1965',
      userID: '68578703777621',
    },
    {
      firstName: 'Melanie',
      lastName: 'Kappel',
      companyname: 'Kappel International',
      street: 'Brittener Str. 34 Britten',
      zipCode: '66679',
      city: 'Losheim am See',
      birthdate: '26.02.1998',
      email: 'einkauf@t-pomline.de',
      userID: '35974639025620',
    },
    {
      firstName: 'Fabian',
      lastName: 'Saller',
      companyname: 'Saller GmbH',
      branch: 'Veranstaltungen',
      street: 'Hubertusstr. 5 Gey',
      zipCode: '52393',
      city: 'Hürtgenwald',
      phone: '01522/16231793',
      homepage: 'http://www.saller.info',
      birthdate: '23.03.1955',
      email: 'fabian@qt-power.info',
      userID: '47201488193811',
    },
    {
      firstName: 'Revelyn',
      lastName: 'Ludwig',
      companyname: 'Ludwig & Partner e.K.',
      street: 'Karlsfeldstr. 15 Friedrichstal',
      zipCode: '76297',
      city: 'Stutensee',
      birthdate: '07.07.1938',
      userID: '56503291539909',
    },
    {
      firstName: 'Kim',
      lastName: 'Höfler',
      companyname: 'Höfler Steuern GbR',
      branch: 'Steuern',
      street: 'Herbststr. 35 ',
      zipCode: '74626',
      city: 'Bretzfeld',
      birthdate: '29.11.1964',
      email: 'hfler@no-addr.de',
      userID: '96653864306320',
    },
    {
      firstName: 'Tim',
      lastName: 'Arbeit',
      companyname: 'Arbeit Forschung OHG',
      branch: 'Forschung',
      street: 'Siemensstr. 16 ',
      zipCode: '85521',
      city: 'Ottobrunn',
      homepage: 'http://www.arbeit.info',
      birthdate: '05.01.1984',
      email: 'marketting@t-pomline.de',
      userID: '41824331322752',
    },
    {
      firstName: 'Lisbeth',
      lastName: 'Koch',
      companyname: 'Koch',
      branch: 'Textil',
      street: 'Renthof 5 ',
      zipCode: '34329',
      city: 'Nieste',
      birthdate: '21.04.1977',
      email: 'lisbeth.koch@comm-prefix.de',
      userID: '23483921198321',
    },
    {
      firstName: 'Rosfriede',
      lastName: 'Schwarz',
      companyname: 'Schwarz',
      branch: 'Forschung',
      street: 'Mittelweg 24 Feldschlößchen',
      zipCode: '01454',
      city: 'Wachau',
      phone: '01514/85418816',
      birthdate: '27.04.1978',
      email: 'rosfriede@blue-white.com',
      userID: '56336811622422',
    },
    {
      firstName: 'Griselda',
      lastName: 'Höfler',
      companyname: 'Höfler GmbH',
      branch: 'Verkehr',
      street: 'Dompfaffstr. 19 Alterlangen',
      zipCode: '91056',
      city: 'Erlangen',
      homepage: 'https://www.hfler.de',
      birthdate: '30.09.1937',
      email: 'logistik@zo-texit.de',
      userID: '39699706727259',
    },
    {
      firstName: 'Karlinda',
      lastName: 'Fiedler',
      companyname: 'Fiedler und Söhne Holding GmbH',
      branch: 'Imobilien',
      street: 'Zum Dorental 17 Misserode',
      zipCode: '37308',
      city: 'Schimberg',
      homepage: 'https://www.fiedler.de',
      birthdate: '01.11.1944',
      email: 'karlinda@technikzq.de',
      userID: '24025894050232',
    },
    {
      firstName: 'Sylke',
      lastName: 'Schulz',
      companyname: 'Schulz & Partner GmbH',
      branch: 'Textil',
      street: 'Theodor-Heuss-Str. 26 ',
      zipCode: '49163',
      city: 'Bohmte',
      homepage: 'https://www.schulz.de',
      birthdate: '27.09.1990',
      email: 'info@zrp-communications.de',
      userID: '76704928474463',
    },
    {
      firstName: 'Helene',
      lastName: 'Baumgarten',
      companyname: 'Baumgarten Versicherung GmbH',
      branch: 'Versicherung',
      street: 'Heinrich-Fausel-Weg 39 ',
      zipCode: '88271',
      city: 'Wilhelmsdorf',
      birthdate: '09.06.1976',
      email: 'marketting@technikzq.de',
      userID: '14268867989727',
    },
    {
      firstName: 'Petja',
      lastName: 'Mann',
      companyname: 'Mann-Team Holding GmbH',
      branch: 'Dienstleistungen',
      street: 'Ringstr. 18 ',
      zipCode: '24994',
      city: 'Osterby',
      phone: '01515/61409426',
      birthdate: '15.05.1997',
      email: 'einkauf@technikzq.net',
      userID: '69263415440066',
    },
    {
      firstName: 'Annina',
      lastName: 'Lange',
      companyname: 'Lange und Söhne GmbH',
      branch: 'Automobil',
      street: 'Ötztaler Str. 6 Darmsheim',
      zipCode: '71069',
      city: 'Sindelfingen',
      birthdate: '17.06.1957',
      email: 'annina@zrp-communications.com',
      userID: '58687466934049',
    },
    {
      firstName: 'Line',
      lastName: 'Busch',
      companyname: 'Busch OHG',
      branch: 'Gastgewerbe',
      street: 'Weidenstr. 2 Affeln',
      zipCode: '58809',
      city: 'Neuenrade',
      phone: '0175/59490021',
      birthdate: '30.07.1952',
      email: 'l.busch@x-piros.info',
      userID: '27261853797838',
    },
    {
      firstName: 'Tenus',
      lastName: 'Schmidt',
      companyname: 'Schmidt-Team GbR',
      branch: 'Handwerk',
      street: 'Bahnhofstr. 34 Kempten',
      zipCode: '87435',
      city: 'Kempten (Allgäu)',
      birthdate: '24.07.1961',
      email: 'schmidt@blue-white.info',
      userID: '51634111713968',
    },
    {
      firstName: 'Leabelle',
      lastName: 'Brantley',
      companyname: 'Brantley-Group',
      branch: 'Recht',
      street: 'Wasserbreite 41A Sandhatten',
      zipCode: '26209',
      city: 'Hatten',
      homepage: 'www.brantley.info',
      birthdate: '16.06.1991',
      email: 'leabelle@technikzq.de',
      userID: '40169249781170',
    },
    {
      firstName: 'Thias',
      lastName: 'Muller',
      companyname: 'Muller GmbH',
      branch: 'Bau',
      street: 'Altenburg 43 ',
      zipCode: '83098',
      city: 'Brannenburg',
      phone: '0179/30906426',
      birthdate: '31.05.1935',
      email: 'thias@t-pomline.de',
      userID: '24735579699812',
    },
    {
      firstName: 'Noella',
      lastName: 'Bischoffs',
      companyname: 'Bischoffs International GmbH & Co. KG',
      street: 'Neuer Weg 24 ',
      zipCode: '39343',
      city: 'Erxleben',
      phone: '0176/77142336',
      birthdate: '21.01.2002',
      email: 'info@technikzq.de',
      userID: '90258799595248',
    },
    {
      firstName: 'Krista',
      lastName: 'Baumann',
      companyname: 'Baumann Energie Verwaltungs GmbH',
      branch: 'Energie',
      street: 'Eichendorffstr. 17 ',
      zipCode: '48703',
      city: 'Stadtlohn',
      phone: '0177/25641181',
      birthdate: '09.08.1948',
      email: 'krista.baumann@technikzq.de',
      userID: '75536387168980',
    },
    {
      firstName: 'Dietbert',
      lastName: 'Wolf',
      companyname: 'Wolf',
      branch: 'Gastgewerbe',
      street: 'Rotkehlchenweg 22 ',
      zipCode: '14547',
      city: 'Beelitz',
      phone: '0162/38406742',
      homepage: 'www.wolf.biz',
      birthdate: '03.11.1960',
      email: 'info@qt-power.de',
      userID: '85539445539073',
    },
    {
      firstName: 'Ringo',
      lastName: 'Große',
      companyname: 'Große Verwaltungs GmbH',
      branch: 'Handwerk',
      street: 'An den Klärteichen 20 Püsselbüren',
      zipCode: '49479',
      city: 'Ibbenbüren',
      phone: '0177/25595888',
      birthdate: '26.03.1947',
      email: 'info@extend.de',
      userID: '70205776699561',
    },
    {
      firstName: 'Basta',
      lastName: 'Schäfer',
      companyname: 'Schäfer Restaurant AG',
      branch: 'Restaurant',
      street: 'Birkenweg 29 ',
      zipCode: '86932',
      city: 'Pürgen',
      phone: '01522/94686893',
      birthdate: '15.04.1982',
      email: 'schfer@extend.net',
      userID: '95764032896104',
    },
    {
      firstName: 'Herbert',
      lastName: 'Bachman',
      companyname: 'Bachman',
      branch: 'Software',
      street: 'Günther-Laukien-Str. 10 Mörsch',
      zipCode: '76287',
      city: 'Rheinstetten',
      birthdate: '07.10.1993',
      email: 'info@zo-texit.com',
      userID: '54525048937935',
    },
    {
      firstName: 'Tido',
      lastName: 'Langer',
      companyname: 'Langer GmbH & Co. KG',
      branch: 'Telekomunikation',
      street: 'Eulenweg 39 Wehberg',
      zipCode: '58507',
      city: 'Lüdenscheid',
      phone: '01512/56145391',
      homepage: 'langer.net',
      birthdate: '01.06.1940',
      email: 'info@blue-white.info',
      userID: '79188813639637',
    },
    {
      firstName: 'Richenza',
      lastName: 'Seidel',
      companyname: 'Seidel-Team GbR',
      branch: 'Chemie',
      street: 'Am Gansberg 31 ',
      zipCode: '09481',
      city: 'Elterlein',
      homepage: 'http://seidel.de',
      birthdate: '05.06.1946',
      email: 'richenza@qt-power.de',
      userID: '68973681342021',
    },
    {
      firstName: 'Babsi',
      lastName: 'Krauss',
      companyname: 'Krauss-Team GmbH',
      branch: 'Bau',
      street: 'Am Becherweg 20 ',
      zipCode: '55270',
      city: 'Ober-Olm',
      birthdate: '28.01.1965',
      email: 'info@x-piros.de',
      userID: '64469281256449',
    },
    {
      firstName: 'Dietlinde',
      lastName: 'Wagner',
      companyname: 'Wagner-Team Verwaltungs GmbH',
      branch: 'Kino',
      street: 'Kreuzbergring 15 Furpach',
      zipCode: '66539',
      city: 'Neunkirchen',
      phone: '0176/80474623',
      birthdate: '18.06.1970',
      email: 'einkauf@extend.com',
      userID: '48091856814324',
    },
    {
      firstName: 'Lientje',
      lastName: 'Höfler',
      companyname: 'Höfler & Partner GbR',
      street: 'Kiefernhain 27 Lenz-Süd',
      zipCode: '17213',
      city: 'Fünfseen',
      homepage: 'http://www.hfler.de',
      birthdate: '11.01.1997',
      email: 'personal@comm-prefix.de',
      userID: '73216324843335',
    },
    {
      firstName: 'Deik',
      lastName: 'Wirth',
      companyname: 'Wirth International GmbH & Co. KG',
      street: 'Zauer Dorfstr. 20 Zaue',
      zipCode: '15913',
      city: 'Schwielochsee',
      phone: '01575/18707349',
      birthdate: '08.07.2002',
      email: 'd.wirth@comm-prefix.de',
      userID: '52866782045717',
    },
    {
      firstName: 'Beath',
      lastName: 'Beckert',
      companyname: 'Beckert',
      branch: 'Handel',
      street: 'Untere Parkstr. 38 ',
      zipCode: '06295',
      city: 'Lutherstadt Eisleben',
      phone: '0176/87242009',
      birthdate: '28.02.1947',
      email: 'info@blue-white.biz',
      userID: '84457154599941',
    },
    {
      firstName: 'Salvina',
      lastName: 'Haberkorn',
      companyname: 'Haberkorn Holding GmbH',
      street: 'Feldstr. 20 ',
      zipCode: '82380',
      city: 'Peißenberg',
      phone: '01573/61492417',
      birthdate: '20.06.1959',
      email: 's.haberkorn@comm-prefix.de',
      userID: '66120726221305',
    },
    {
      firstName: 'Hanneli',
      lastName: 'Wruck',
      companyname: 'Wruck Versicherung Holding GmbH',
      branch: 'Versicherung',
      street: 'Broichkirchweg 29 Kelz',
      zipCode: '52391',
      city: 'Vettweiß',
      birthdate: '17.04.1953',
      userID: '54961597546758',
    },
    {
      firstName: 'Londar',
      lastName: 'Tschida',
      companyname: 'Tschida-Group AG',
      branch: 'Bau',
      street: 'Saßnitzer Weg 28 Rahlstedt',
      zipCode: '22147',
      city: 'Hamburg',
      phone: '0163/88179989',
      birthdate: '24.05.1975',
      email: 'l.tschida@x-piros.com',
      userID: '68740529113648',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Brose',
      companyname: 'Brose-Group',
      branch: 'Pharmazie',
      street: 'Markusstr. 1B Pfaffenrot',
      zipCode: '76359',
      city: 'Marxzell',
      phone: '01517/43018473',
      homepage: 'www.brose.com',
      birthdate: '07.03.1963',
      email: 'info@no-addr.net',
      userID: '24055098054842',
    },
    {
      firstName: 'Samoa',
      lastName: 'Graner',
      companyname: 'Graner & Partner AG',
      branch: 'Bildung',
      street: 'Carl-Meyer-Str. 12 Böhlitz-Ehrenberg',
      zipCode: '04178',
      city: 'Leipzig',
      phone: '01573/32859099',
      birthdate: '25.01.1935',
      email: 'logistik@t-pomline.de',
      userID: '22481197890186',
    },
    {
      firstName: 'Marie Luise',
      lastName: 'Lewerentz',
      companyname: 'Lewerentz Media AG',
      branch: 'Media',
      street: 'Königsberger Str. 26 ',
      zipCode: '65830',
      city: 'Kriftel',
      phone: '0176/61982093',
      homepage: 'www.lewerentz.net',
      birthdate: '31.05.1934',
      email: 'marieluise.lewerentz@zrp-communications.de',
      userID: '25850296317081',
    },
    {
      firstName: 'Sebastian',
      lastName: 'Vogel',
      companyname: 'Vogel-Group GmbH',
      street: 'Oranienstr. 25 Langenhain',
      zipCode: '65719',
      city: 'Hofheim am Taunus',
      phone: '01516/77590250',
      birthdate: '28.08.1942',
      email: 'einkauf@zo-texit.com',
      userID: '76078395669809',
    },
    {
      firstName: 'Archus',
      lastName: 'Oppenheimer',
      companyname: 'Oppenheimer-Group GmbH',
      branch: 'Dienstleistungen',
      street: 'In der Reitenwies 2 Theley',
      zipCode: '66636',
      city: 'Tholey',
      phone: '01570/69112937',
      homepage: 'http://www.oppenheimer.de',
      birthdate: '15.10.1942',
      email: 'archus@t-pomline.com',
      userID: '82745099798788',
    },
    {
      firstName: 'Florian',
      lastName: 'Kerner',
      companyname: 'Kerner-Group GmbH',
      street: 'Im Meilesfeld 3 Marksuhl',
      zipCode: '99834',
      city: 'Gerstungen',
      homepage: 'http://www.kerner.com',
      birthdate: '01.02.1949',
      email: 'f.kerner@zrp-communications.de',
      userID: '11762867755264',
    },
    {
      firstName: 'Lars',
      lastName: 'Reier',
      companyname: 'Reier Holding GmbH',
      branch: 'Gesundheit',
      street: 'Seidiek 19 Lembeck',
      zipCode: '46286',
      city: 'Dorsten',
      birthdate: '26.03.2002',
      email: 'logistik@qt-power.de',
      userID: '39364079884599',
    },
    {
      firstName: 'Franziskus',
      lastName: 'Blumenthal',
      companyname: 'Blumenthal Kino AG',
      street: 'Gildestr. 5 ',
      zipCode: '48465',
      city: 'Schüttorf',
      homepage: 'www.blumenthal.de',
      birthdate: '28.10.1976',
      userID: '72944755471714',
    },
    {
      firstName: 'Denise',
      lastName: 'Becker',
      companyname: 'Becker-Team',
      branch: 'Restaurant',
      street: 'Ostfriesenweg 23 Rahrdum',
      zipCode: '26441',
      city: 'Jever',
      birthdate: '22.04.1941',
      email: 'becker@no-addr.info',
      userID: '14541552871346',
    },
    {
      firstName: 'Bendine',
      lastName: 'Beckert',
      companyname: 'Beckert-Team Verwaltungs GmbH',
      branch: 'Ärzte',
      street: 'Am Hegeberg 18 Viermünden',
      zipCode: '35066',
      city: 'Frankenberg',
      birthdate: '03.05.1984',
      email: 'bendine@company.net',
      userID: '45056645433022',
    },
    {
      firstName: 'Kastulus',
      lastName: 'Baasch',
      companyname: 'Baasch und Söhne e.K.',
      branch: 'Elektroinstallationen',
      street: 'Von-Frays-Str. 38 Pasing-Obermenzing',
      zipCode: '81245',
      city: 'München',
      phone: '0172/69513876',
      birthdate: '15.10.1945',
      email: 'marketting@blue-white.de',
      userID: '31211014482881',
    },
    {
      firstName: 'Sophie',
      lastName: 'Kranz',
      companyname: 'Kranz International',
      branch: 'Energie',
      street: 'Diekenkamp 25 ',
      zipCode: '26419',
      city: 'Schortens',
      birthdate: '26.06.1952',
      userID: '63188719209362',
    },
  ];

  user: User = new User();
  genders: string[] = ['Male', 'Female', 'Divers'];

  loading: boolean = false;

  constructor(
    public dialogRef: MatDialogRef<DialogAddUserComponent>,
    private firestore: Firestore,
    private _formBuilder: FormBuilder
  ) {
    console.log('FirstFormGroup', this.firstFormGroup);
    console.log(this.firstFormGroup.controls.birthdate2);
    console.log(
      new Date(
        'Tue Nov 08 2022 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)'
      )
    );
  }

  ngOnInit(): void {}

  closeDialog(): void {
    this.dialogRef.close();
  }

  saveUser() {
    this.loading = true;

    this.user.firstName = this.firstFormGroup.controls.firstName2.value;
    this.user.lastName = this.firstFormGroup.controls.lastName2.value;
    this.user.birthdate = this.firstFormGroup.controls.birthdate2.value
      ? convert(this.firstFormGroup.controls.birthdate2.value)
      : '';

    this.user.street = this.secondFormGroup.controls.street.value;
    this.user.zipCode = this.secondFormGroup.controls.zipCode.value;
    this.user.city = this.secondFormGroup.controls.city.value;

    this.user.email = this.thirdFormGroup.controls.email.value;
    this.user.phone = this.thirdFormGroup.controls.phone.value
      ? this.thirdFormGroup.controls.phone.value
      : '';

    this.user.userID = this.user.createID(20);

    this.createFirestoreUser();
    this.closeDialog();
    console.log(this.user);
    this.loading = false;
  }

  createFirestoreUser() {
    const userRef = collection(this.firestore, 'users');
    setDoc(doc(userRef, this.user.userID), this.user.toJson());
  }

  getErrorMessage(x: FormControl, y: string) {
    if (x.hasError('required')) {
      return 'You must enter a value';
    }

    return x.hasError('pattern') ? `Not a valid ${y}` : '';
  }
}

function convert(str: any) {
  var date = new Date(str),
    mnth = ('0' + (date.getMonth() + 1)).slice(-2),
    day = ('0' + date.getDate()).slice(-2);
  return [day, mnth, date.getFullYear()].join('.');
}
